export { default as TestSingle } from './single.vue'
export { default as TestUserinfo } from './userinfo.vue'
export { default as TestRadio } from './radio.vue'
export { default as TestJudge } from './radio.vue'
export { default as TestCheckbox } from './checkbox.vue'